micronaut:
  application:
    name: micronaut-rest
  server:
    port: 30310
    netty:
      logLevel: TRACE

grpc:
  channels:
    casadocodigo:
      address: '${KEYMANAGER_SERVER:`localhost:3030`}'
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false